seed: 42
num_scenarios: 1
max_steps: 500
simulation_dir: "output/tst"

randomization:
  num_trains:
    min: 1
    max: 1
  grid_width:
    min: 20
    max: 50
  grid_height:
    min: 20
    max: 50
  num_cities:
    min: 2
    max: 5
  max_rails_between_cities:
    min: 1
    max: 3
  max_rail_pairs_in_city:
    min: 1
    max: 3
